# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in rumale-metric_learning.gemspec
gemspec

gem 'rumale-core', path: '../rumale-core'
gem 'rumale-decomposition', path: '../rumale-decomposition'
gem 'rumale-evaluation_measure', path: '../rumale-evaluation_measure'
gem 'rumale-nearest_neighbors', path: '../rumale-nearest_neighbors'
gem 'rumale-preprocessing', path: '../rumale-preprocessing'

gem 'numo-tiny_linalg', '~> 0.3.1'
gem 'rake', '~> 13.0'
gem 'rspec', '~> 3.0'
gem 'rubocop', '~> 1.21'
gem 'rubocop-performance', '~> 1.8'
gem 'rubocop-rake', '~> 0.5'
gem 'rubocop-rspec', '~> 2.27.0'
gem 'simplecov', '~> 0.21'
