# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in rumale-linear_model.gemspec
gemspec

gem 'rumale-core', path: '../rumale-core'

gem 'numo-tiny_linalg', '~> 0.3.1'
gem 'parallel', '~> 1.22'
gem 'rake', '~> 13.0'
gem 'rspec', '~> 3.0'
gem 'simplecov', '~> 0.21'

eval_gemfile(File.expand_path('../Gemfile.rubocop', __dir__))
