# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in rumale-model_selection.gemspec
gemspec

gem 'rumale-core', path: '../rumale-core'
gem 'rumale-evaluation_measure', path: '../rumale-evaluation_measure'
gem 'rumale-pipeline', path: '../rumale-pipeline'
gem 'rumale-preprocessing', path: '../rumale-preprocessing'
gem 'rumale-kernel_approximation', path: '../rumale-kernel_approximation'
gem 'rumale-kernel_machine', path: '../rumale-kernel_machine'
gem 'rumale-linear_model', path: '../rumale-linear_model'
gem 'rumale-tree', path: '../rumale-tree'
gem 'rumale-naive_bayes', path: '../rumale-naive_bayes'

gem 'rake', '~> 13.0'
gem 'rspec', '~> 3.0'
gem 'simplecov', '~> 0.21'

eval_gemfile(File.expand_path('../Gemfile.rubocop', __dir__))
