
require 'numo/narray'

require 'svmkit/version'
require 'svmkit/pairwise_metric'
require 'svmkit/base/base_estimator'
require 'svmkit/base/classifier'
require 'svmkit/base/transformer'
require 'svmkit/kernel_approximation/rbf'
require 'svmkit/linear_model/pegasos_svc'
require 'svmkit/linear_model/logistic_regression'
require 'svmkit/kernel_machine/kernel_svc'
require 'svmkit/multiclass/one_vs_rest_classifier'
require 'svmkit/preprocessing/l2_normalizer'
require 'svmkit/preprocessing/min_max_scaler'
require 'svmkit/preprocessing/standard_scaler'
