# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in rumale-feature_extraction.gemspec
gemspec

gem 'rumale-core', path: '../rumale-core'

gem 'rake', '~> 13.0'
gem 'rspec', '~> 3.0'
gem 'rubocop', '~> 1.21'
gem 'rubocop-performance', '~> 1.8'
gem 'rubocop-rake', '~> 0.5'
gem 'rubocop-rspec', '~> 2.27.0'
gem 'simplecov', '~> 0.21'
