# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in rumale-kernel_machine.gemspec
gemspec

gem 'rumale-core', path: '../rumale-core'
gem 'rumale-decomposition', path: '../rumale-decomposition'
gem 'rumale-evaluation_measure', path: '../rumale-evaluation_measure'
gem 'rumale-linear_model', path: '../rumale-linear_model'
gem 'rumale-nearest_neighbors', path: '../rumale-nearest_neighbors'
gem 'rumale-preprocessing', path: '../rumale-preprocessing'

gem 'numo-tiny_linalg', '~> 0.3.1'
gem 'parallel', '~> 1.22'
gem 'rake', '~> 13.0'
gem 'rspec', '~> 3.0'
gem 'simplecov', '~> 0.21'

eval_gemfile(File.expand_path('../Gemfile.rubocop', __dir__))
