name: build

on:
  push:
    branches:
      - main
      - dev*
      - v[0-9]+.[0-9]+.[0-9]+
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build-mac:
    runs-on: macos-latest
    name: Ruby 3.4 (macOS)
    steps:
    - uses: actions/checkout@v5
    - name: Install OpenBLAS
      run: |
        brew update
        brew install openblas
        brew info openblas
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4
    - name: Build and test with Rake
      run: |
        bundle config --global build.numo-tiny_linalg "--with-opt-dir=/opt/homebrew/opt/openblas"
        bash rumale-test.sh
